# ruff: noqa: PYI051

from collections.abc import Mapping, Sequence
from typing import Literal, TypeAlias

from lupo import Step

Ostr: TypeAlias = str | None
Obool: TypeAlias = bool | None
Oint: TypeAlias = int | None


def setup_node(
    *,
    name: Ostr = None,
    version: str = 'v6',
    node_version: Ostr = None,
    node_version_file: Ostr = None,
    check_latest: Obool = None,
    architecture: Ostr = None,
    token: Ostr = None,
    cache: Literal['npm', 'yarn', 'pnpm'] | None = None,
    package_manager_cache: Obool = None,
    cache_dependency_path: Ostr = None,
    registry_url: Ostr = None,
    scope: Ostr = None,
    mirror: Ostr = None,
    mirror_token: Ostr = None,
    args: Ostr = None,
    entrypoint: Ostr = None,
    condition: Ostr = None,
    working_directory: Ostr = None,
    shell: Ostr = None,
    id: Ostr = None,  # noqa: A002
    env: Mapping[str, str] | None = None,
    continue_on_error: Ostr = None,
    timeout_minutes: Ostr = None,
) -> Step: ...


def setup_python(
    *,
    name: Ostr = None,
    version: str = 'v6',
    python_version: Ostr = None,
    python_version_file: Ostr = None,
    check_latest: Obool = None,
    architecture: Ostr = None,
    token: Ostr = None,
    cache: Literal['pip', 'pipenv', 'poetry'] | None = None,
    package_manager_cache: Obool = None,
    cache_dependency_path: Ostr = None,
    update_environment: Obool = None,
    allow_prereleases: Obool = None,
    freethreaded: Obool = None,
    pip_versions: Ostr = None,
    pip_install: Ostr = None,
    args: Ostr = None,
    entrypoint: Ostr = None,
    condition: Ostr = None,
    working_directory: Ostr = None,
    shell: Ostr = None,
    id: Ostr = None,  # noqa: A002
    env: Mapping[str, str] | None = None,
    continue_on_error: Ostr = None,
    timeout_minutes: Ostr = None,
) -> Step: ...


def setup_go(
    *,
    name: Ostr = None,
    version: str = 'v6',
    go_version: Ostr,
    go_version_file: Ostr,
    check_latest: Obool,
    architecture: Ostr,
    token: Ostr,
    cache: Obool,
    cache_dependency_path: Ostr,
    args: Ostr = None,
    entrypoint: Ostr = None,
    condition: Ostr = None,
    working_directory: Ostr = None,
    shell: Ostr = None,
    id: Ostr = None,  # noqa: A002
    env: Mapping[str, str] | None = None,
    continue_on_error: Ostr = None,
    timeout_minutes: Ostr = None,
) -> Step: ...


def setup_rust(
    *,
    name: Ostr = None,
    version: str = 'v1',
    toolchain: Ostr,
    target: Ostr = None,
    components: Sequence[str] | None = None,
    cache: Obool = None,
    cache_directories: Sequence[str] | None = None,
    cache_workspaces: Sequence[str] | None = None,
    cache_on_failure: Obool = None,
    cache_key: Ostr = None,
    cache_shared_key: Ostr = None,
    cache_bin: Obool = None,
    cache_provider: Literal['github', 'buildjet', 'warpbuild'] | None = None,
    cache_all_crates: Obool = None,
    cache_workspace_crates: Obool = None,
    matcher: Obool = None,
    rustflags: Ostr = None,
    override: Obool = None,
    rust_src_dir: Ostr = None,
    args: Ostr = None,
    entrypoint: Ostr = None,
    condition: Ostr = None,
    working_directory: Ostr = None,
    shell: Ostr = None,
    id: Ostr = None,  # noqa: A002
    env: Mapping[str, str] | None = None,
    continue_on_error: Ostr = None,
    timeout_minutes: Ostr = None,
) -> Step: ...


def install_rust_tool(
    *,
    tool: Sequence[
        Literal[
            'biome',
            'cargo-audit',
            'cargo-auditable',
            'cargo-binstall',
            'cargo-careful',
            'cargo-cyclonedx',
            'cargo-deadlinks',
            'cargo-deny',
            'cargo-dinghy',
            'cargo-export',
            'cargo-hack',
            'cargo-insta',
            'cargo-lambda',
            'cargo-llvm-cov',
            'cargo-machete',
            'cargo-make',
            'cargo-minimal-versions',
            'cargo-nextest',
            'cargo-no-dev-deps',
            'cargo-rdme',
            'cargo-semver-checks',
            'cargo-shear',
            'cargo-sort',
            'cargo-spellcheck',
            'cargo-tarpaulin',
            'cargo-udeps',
            'cargo-valgrind',
            'cargo-zigbuild',
            'coreutils',
            'cross',
            'cyclonedx',
            'deepsource',
            'dprint',
            'earthly',
            'editorconfig-checker',
            'espup',
            'git-cliff',
            'grcov',
            'hyperfine',
            'iai-callgrind-runner',
            'jaq',
            'just',
            'knope',
            'martin',
            'mdbook',
            'mdbook-alerts',
            'mdbook-linkcheck',
            'mdbook-mermaid',
            'mdbook-mermaid-ssr',
            'mise',
            'osv-scanner',
            'parse-changelog',
            'parse-dockerfile',
            'prek',
            'protoc',
            'rclone',
            'release-plz',
            'sccache',
            'shellcheck',
            'shfmt',
            'syft',
            'taplo',
            'tombi',
            'trivy',
            'trunk',
            'typos',
            'ubi',
            'uv',
            'vacuum',
            'valgrind',
            'wait-for-them',
            'wash',
            'wasm-bindgen',
            'wasm-pack',
            'wasmtime',
            'xbuild',
            'xh',
            'zizmor',
            'zola',
        ]
        | str
    ],
    name: Ostr = None,
    version: str = 'v2',
    checksum: Obool = None,
    fallback: Ostr = None,
    args: Ostr = None,
    entrypoint: Ostr = None,
    condition: Ostr = None,
    working_directory: Ostr = None,
    shell: Ostr = None,
    id: Ostr = None,  # noqa: A002
    env: Mapping[str, str] | None = None,
    continue_on_error: Ostr = None,
    timeout_minutes: Ostr = None,
) -> Step: ...


def setup_uv(
    *,
    name: Ostr = None,
    version: str = 'v7',
    uv_version: Ostr = None,
    uv_version_file: Ostr = None,
    resolution_strategy: Ostr = None,
    python_version: Ostr = None,
    activate_environment: Obool = None,
    uv_working_directory: Ostr = None,
    checksum: Ostr = None,
    github_token: Ostr = None,
    enable_cache: Literal['auto'] | bool | None = None,
    cache_dependency_glob: Sequence[str] | None = None,
    restore_cache: Obool = None,
    save_cache: Obool = None,
    cache_suffix: Ostr = None,
    cache_local_path: Ostr = None,
    prune_cache: Obool = None,
    cache_python: Obool = None,
    ignore_nothing_to_cache: Obool = None,
    ignore_empty_workdir: Obool = None,
    tool_dir: Ostr = None,
    tool_bin_dir: Ostr = None,
    manifest_file: Ostr = None,
    add_problem_matchers: Obool = None,
    args: Ostr = None,
    entrypoint: Ostr = None,
    condition: Ostr = None,
    working_directory: Ostr = None,
    shell: Ostr = None,
    id: Ostr = None,  # noqa: A002
    env: Mapping[str, str] | None = None,
    continue_on_error: Ostr = None,
    timeout_minutes: Ostr = None,
) -> Step: ...


__all__ = ['install_rust_tool', 'setup_go', 'setup_node', 'setup_python', 'setup_rust', 'setup_uv']
